### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by aerhard**
This PR provides validation rules and the `mei-all.rng` schema to support validation / autocomplete with the https://atom.io/packages/linter-autocomplete-jing package even when no schema references (xml-model processing instructions) exist in an XML document. I've also simplified the grammar, removed the specs folder and the snippets (which are available by inheritance from the `text.xml` grammar)

### CODE REVIEW

**Comment by rettinghaus** [comment]
Could that please get merged?

**Comment by crantila** [comment]
Hi! I'm very sorry, but somehow I didn't notice this pull request until just now. If you would like to propose future enhancements, please don't hesitate to ping me if I don't respond quickly!

**Comment by rettinghaus** [comment]
@crantila could you release a new version, so that it's available as Atom package?

**Comment by crantila** [comment]
Sorry again for the wait&mdash;I've finally updated the Atom package!

**Pull request merged**
